# docker compose -p dev -f docker-compose.yaml -f docker-compose.prod.yaml up;

x-logging: &loki-logging-prod
  driver: loki
  options:
    loki-url: "http://localhost:9002/loki/api/v1/push"
    loki-retries: 2
    loki-timeout: 1s
    loki-max-backoff: 800ms
    max-size: "10m"
    max-file: "3"

services:
  relay:
    container_name: relay
    logging: *loki-logging-prod
    restart: always
    build:
      dockerfile: ./Dockerfile
    environment:
      - ADMIN_TOKEN
    ports:
      - "9005:3000"
